Repository KCS-Second-Project/StepStory-Client, pull requests merged in 2024-03, with the labels that each got.

#7 ✨Feat: 댓글 컴포넌트 추가, 상태관리 통한 댓글 토글 기능 추가, 이미지에 인덱스 및 장소명 추가, 구글 맵을 통한 여행지 표현, 캘린더를 통한 여행기간 표현 추가
  stepstory/package-lock.json
  stepstory/package.json
  stepstory/src/App.js
  stepstory/src/apis/GoogleMapsApi.js
  stepstory/src/assets/images/defaultprofile.png
  stepstory/src/components/Buttons/CommentButton/CommentButton.jsx
  stepstory/src/components/Comment/Comment.jsx
  stepstory/src/components/Comment/style.css
  stepstory/src/components/Header/Header.jsx
  stepstory/src/components/Header/style.css
  stepstory/src/components/ImageSlider/ImageSlider.jsx
  stepstory/src/components/ImageSlider/style.css
  stepstory/src/components/Map/Map.jsx
  stepstory/src/components/Map/style.css
  stepstory/src/components/PageLayout/ViewPostLayout.jsx
  stepstory/src/components/PageLayout/style.css
  stepstory/src/components/PostCard/PostCard.jsx
  stepstory/src/components/PostCard/style.css
  stepstory/src/components/PostComments/PostComments.jsx
  stepstory/src/components/PostComments/style.css
  stepstory/src/components/PostContent/PostContent.jsx
  stepstory/src/components/PostContent/style.css
  stepstory/src/components/TravelPeriod/TravelPeriod.jsx
  stepstory/src/components/TravelPeriod/style.css
  stepstory/src/components/UserProfile/UserProfile.jsx
  stepstory/src/components/UserProfile/style.css
Labels: feature, 동겸

#11 ✨Feat: 로그인, 유저별 회원정보 입력, PostStep1 화면 구성 구현
  stepstory/package-lock.json
  stepstory/package.json
  stepstory/src/App.css
  stepstory/src/App.js
  stepstory/src/components/Login/login.css
  stepstory/src/components/Login/login.jsx
  stepstory/src/components/PostStep1/calendar.jsx
  stepstory/src/components/PostStep1/map.jsx
  stepstory/src/components/PostStep1/step1.css
  stepstory/src/components/PostStep1/step1.jsx
  stepstory/src/components/Sign/sign.css
  stepstory/src/components/Sign/sign.jsx
  stepstory/src/components/SocialSign/socialsign.css
  stepstory/src/components/SocialSign/socialsign.jsx
  stepstory/src/image/crown.png
  stepstory/src/image/loginGoogle.png
  stepstory/src/image/loginKakao.png
  stepstory/src/image/logo.svg
  stepstory/src/image/uploadImg.png
  stepstory/src/index.js
  stepstory/src/logo.svg
  stepstory/src/logo_react.svg
  stepstory/yarn.lock
Labels: feature, 혜인

#14 ✨Feat: Main, FriendStory, MysStory 화면 구성 완료, Footer 추가
  stepstory/package-lock.json
  stepstory/package.json
  stepstory/src/App.js
  stepstory/src/components/Buttons/FriendpageButton/FriendpageButton.css
  stepstory/src/components/Buttons/FriendpageButton/FriendpageButton.jsx
  stepstory/src/components/Footer/footer.css
  stepstory/src/components/Footer/footer.jsx
  stepstory/src/components/FriendStory/FriendStory.css
  stepstory/src/components/FriendStory/FriendStory.jsx
  stepstory/src/components/Login/login.jsx
  stepstory/src/components/Main/Main.css
  stepstory/src/components/Main/Main.jsx
  stepstory/src/components/Map/style.css
  stepstory/src/components/MyStory/MyStory.css
  stepstory/src/components/MyStory/MyStory.jsx
  stepstory/src/components/PostStep1/map.jsx
  stepstory/src/components/PostStep1/step1.css
  stepstory/src/components/PostStep1/step1.jsx
  stepstory/src/components/Sign/sign.jsx
  stepstory/src/components/SocialSign/socialsign.jsx
  stepstory/src/image/Blogo.svg
  stepstory/src/image/CloseD.png
  stepstory/src/image/OpenD.png
  stepstory/src/image/Wlogo.svg
  stepstory/src/index.js
  stepstory/yarn.lock
Labels: feature, 혜인

#19 ✨ PostStep2, PostStep3 컴포넌트 구현 및 페이지 구현
  stepstory/src/apis/GoogleMapsApi.js
  stepstory/src/assets/images/buttons/backpagebutton.png
  stepstory/src/assets/images/buttons/nextpagebutton.png
  stepstory/src/components/Buttons/BackPageButton/BackPageButton.jsx
  stepstory/src/components/Buttons/BackPageButton/style.css
  stepstory/src/components/Buttons/NextPageButton/NextPageButton.jsx
  stepstory/src/components/Buttons/NextPageButton/style.css
  stepstory/src/components/Header/Header.jsx
  stepstory/src/components/Header/style.css
  stepstory/src/components/Map/Map.jsx
  stepstory/src/components/Map/style.css
  stepstory/src/components/PageLayout/style.css
  stepstory/src/components/PostStep2Main/PostStep2Main.jsx
  stepstory/src/components/PostStep2Main/style.css
  stepstory/src/components/PostStep3Main/PostStep3Main.jsx
  stepstory/src/components/PostStep3Main/style.css
  stepstory/src/components/TravelPeriod/TravelPeriod.jsx
  stepstory/src/components/TravelPeriod/style.css
  stepstory/src/index.js
  stepstory/src/pages/PostStep2/PostStep2.jsx
  stepstory/src/pages/PostStep2/style.css
  stepstory/src/pages/PostStep3/PostStep3.jsx
  stepstory/src/pages/PostStep3/style.css
  stepstory/src/pages/ViewPost/ViewPost.jsx
  stepstory/src/pages/ViewPost/style.css
  stepstory/yarn.lock
Labels: feature, 동겸

#20 🐛 소셜로그인 url 수정 및 페이지 분할 / 라우팅 설정 및 회원가입 api 연결
  stepstory/Test.jsx
  stepstory/package-lock.json
  stepstory/package.json
  stepstory/src/App.js
  stepstory/src/App.jsx
  stepstory/src/App.test.js
  stepstory/src/apis/axios.js
  stepstory/src/apis/emailCheck.js
  stepstory/src/apis/onSignUp.js
  stepstory/src/components/LeftPane/LeftPane.jsx
  stepstory/src/components/Login/login.jsx
  stepstory/src/components/Sign/sign.jsx
  stepstory/src/index.js
  stepstory/src/pages/Main/Main.css
  stepstory/src/pages/Main/Main.jsx
  stepstory/src/pages/PostStep1/PostStep1.jsx
  stepstory/src/pages/PostStep1/calendar.jsx
  stepstory/src/pages/PostStep1/style.css
  stepstory/src/routers.jsx
  stepstory/src/setupTests.js
  stepstory/yarn.lock
Labels: bug, fix, 동겸

#24 ✨ 폼로그인 및 main에서 user 정보 불러오기 완료
  stepstory/package-lock.json
  stepstory/src/components/Login/login.jsx
  stepstory/src/index.js
  stepstory/src/pages/Main/Main.jsx
  stepstory/yarn.lock
Labels: feature, 동겸

#25 ✨ ViewPost 통신 로직 구현 / signUp 완료 버튼 활성화 조건 변경
  stepstory/src/components/Sign/sign.jsx
  stepstory/src/pages/ViewPost/ViewPost.jsx
Labels: feature, 동겸

#27 ✨ feat: 로그아웃 통신 구현
  stepstory/src/components/LeftPane/LeftPane.jsx
Labels: feature, 동겸

#28 🐛fix: 로그아웃 오류 수정
  stepstory/src/components/LeftPane/LeftPane.jsx
Labels: bug, 동겸

#29 🐛fix: 로그아웃 오류 수정
  stepstory/src/components/LeftPane/LeftPane.jsx
Labels: bug, 동겸

#30 ✨ 로그아웃 통신 구현 완료
  stepstory/src/components/LeftPane/LeftPane.jsx
Labels: feature, 동겸

#34 🐛fix: 회원가입 회원정보수정 로직 수정
  stepstory/src/components/Sign/sign.jsx
Labels: bug, 동겸
